### ISSUE TITLE
Bitbucket ?

### ISSUE THREAD

**Issue by joeblew99** [agrison/harpoon#2]
Do you know if this works with bitbucket ?
Also if I run this on a computerthat's behind NAT, how is the program alerted to changes in the git server ? Is it polling ?

**Comment by agrison** [comment]
I does only support GitHub for the moment since the application is waiting for a HTTP POST request with both GitHub' specific headers and payload.
But its doable, Bitbucket propose the same functionality, see: [https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html](https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html)

Harpoon is not polling, it does listen on a configurable ip and port for HTTP requests emitted by GitHub when an event occurs on your repository.

**Comment by agrison** [comment]
FYI atlassian has a project ready to fork and run specifically for their needs: https://bitbucket.org/atlassianlabs/webhook-listener

**Comment by joeblew99** [comment]
Thanks all.

So my machine need a public static IP ? Did not get a clear answer.
Ah but the bitbucket example is using ngrok, so its faking the NAT up to a
public static IP.

Suggest harpoon maybe does the same

**Comment by agrison** [comment]
Yes you need a public IP where GitHub can POST. But as you said you can configure ngrok for this. 
To be clear, I'm using harpoon on a server public IP behind nginx so I didn't thought about that problem of public IP on a machine behind a NAT. Same goes for the support of Bitbucket that I do not use.

I'll take a look at it, but if it's already doable using ngrok I propose you do that for the moment

**Comment by joeblew99** [comment]
Ok that clear now thanks for your patience.

**Comment by agrison** [comment]
Hey @joeblew99, you can take a look, I just added an option for tunneling using https://localtunnel.me/, I've tested it a little on my side and it seems to be working OK.

Hope that helps :smile_cat:

**Comment by joeblew99** [comment]
Awesome.

I will try it when I get a chance. I am in the middle of a sprint, so have
to wait.
